import { expect, it, vi } from 'vitest'
import { createCollector } from '../src/collector.ts'
import type { TelemetryStore } from '../src/store.ts'
import type { TelemetryRecordV1 } from '../src/contracts.ts'
const started = (seq = 1) => ({ seq, type: 'dsh-plugin/run-started', data: { schemaVersion: 1, mode: 'direct', provider: 'secret-provider', model: 'secret-model' } })
const budget = (seq = 2) => ({ seq, type: 'dsh-plugin/budget-rejected', data: { schemaVersion: 1, reason: 'secret-reason', observed: 2, limit: 1 } })
function setup() {
  const records: TelemetryRecordV1[] = []
  const store: TelemetryStore = { salt: new Uint8Array(32).fill(1), enqueue: vi.fn(record => { records.push(record); return true }), flush: vi.fn(async () => {}), dispose: vi.fn(async () => {}), stats: () => ({ queued: 0, dropped: 0, writeErrors: 0 }) }
  return { records, store, collector: createCollector(store) }
}
it('deduplicates canonical sequence per session and seals root after accepted descendants', async () => {
  const { collector, records, store } = setup()
  collector.observe({ id: 'root' }, started())
  collector.observe({ id: 'root' }, started())
  collector.observe({ id: 'child', parentId: 'root' }, budget(1))
  collector.observe({ id: 'grandchild', parentId: 'child' }, budget(1))
  expect(collector.stats().trackedRuns).toBe(1)
  collector.closeRoot('child')
  expect(records).toHaveLength(3)
  collector.closeRoot('root')
  collector.observe({ id: 'child', parentId: 'root' }, budget(2))
  collector.observe({ id: 'root' }, started())
  await collector.flush()
  expect(records.map(r => 'seq' in r ? r.seq : r.kind)).toEqual([1, 2, 3, 'run-seal'])
  expect(records[3]).toMatchObject({ observationCount: 3, complete: true, lostCount: 0 })
  expect(collector.stats()).toMatchObject({ trackedRuns: 0, dropped: 2 })
  expect(store.flush).toHaveBeenCalled()
  expect(JSON.stringify(records)).not.toContain('secret')
  await collector.dispose()
})
it('ignores unrelated events and rejects unknown parents and late root admission', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'unseen' }, { seq: 1, type: 'agent/request-error', data: new Error('secret') })
  expect(collector.stats().dropped).toBe(0)
  collector.observe({ id: 'child', parentId: 'missing' }, budget())
  collector.observe({ id: 'late' }, budget())
  collector.observe({ id: 'late' }, started())
  expect(collector.stats().dropped).toBe(3)
  expect(records).toHaveLength(0)
  await collector.dispose()
})
it('caps active roots and stops a root at 2048 events without losing its incomplete state', async () => {
  const { collector, records } = setup()
  for (let i = 0; i < 65; i++) collector.observe({ id: `r${i}` }, started())
  expect(collector.stats().trackedRuns).toBe(64)
  for (let i = 2; i <= 2049; i++) collector.observe({ id: 'r0' }, budget(i))
  collector.closeRoot('r0')
  expect(records.at(-1)).toMatchObject({ observationCount: 2048, complete: false, lostCount: 1 })
  await collector.flush()
  expect(collector.stats().dropped).toBe(2)
  await collector.dispose()
  expect(collector.stats().trackedRuns).toBe(0)
  expect(records.at(-1)).toMatchObject({ complete: false })
})
it('counts malformed projection and queue rejection as loss, never resets on flush', async () => {
  const { collector, store, records } = setup()
  collector.observe({ id: 'root' }, started())
  collector.observe({ id: 'root' }, { ...budget(), data: {} })
  vi.mocked(store.enqueue).mockImplementationOnce(() => false)
  collector.observe({ id: 'root' }, budget(3))
  collector.closeRoot('root')
  await collector.flush()
  expect(records.at(-1)).toMatchObject({ observationCount: 1, lostCount: 2, complete: false })
  expect(collector.stats().dropped).toBe(2)
  await collector.dispose()
})
it('failed seal admission leaves no complete seal', async () => {
  const { collector, store, records } = setup()
  collector.observe({ id: 'root' }, started())
  vi.mocked(store.enqueue).mockImplementationOnce(() => false)
  collector.closeRoot('root')
  expect(records).toHaveLength(1)
  expect(collector.stats().dropped).toBe(1)
  await collector.dispose()
})
it('schedules and catches background writes and rejects explicit flush generically', async () => {
  const { collector, store } = setup()
  vi.mocked(store.flush).mockRejectedValue(new Error('/secret/path'))
  collector.observe({ id: 'root' }, started())
  await new Promise(resolve => setImmediate(resolve))
  expect(store.flush).toHaveBeenCalled()
  await expect(collector.flush()).rejects.toThrow('telemetry collector write failed')
  expect(collector.stats().writeErrors).toBe(1)
  await collector.dispose()
  expect(store.dispose).toHaveBeenCalledTimes(1)
})
it('uses a fresh run identity each generation and disposes once with incomplete open seals', async () => {
  const one = setup(); const two = setup()
  one.collector.observe({ id: 'root' }, started()); two.collector.observe({ id: 'root' }, started())
  expect(one.records[0].runRef).not.toBe(two.records[0].runRef)
  expect(one.records[0].domainRef).toBe(two.records[0].domainRef)
  await Promise.all([one.collector.dispose(), one.collector.dispose()])
  one.collector.observe({ id: 'new' }, started())
  expect(one.store.dispose).toHaveBeenCalledTimes(1)
  expect(one.records.at(-1)).toMatchObject({ complete: false })
  expect(one.records).toHaveLength(2)
  await two.collector.dispose()
})
it('fails closed after bounded retirement capacity, preserving current roots', async () => {
  const { collector, records } = setup()
  for (let i = 0; i < 2048; i++) { collector.observe({ id: `r${i}` }, started()); collector.closeRoot(`r${i}`) }
  collector.observe({ id: 'overflow' }, started())
  collector.observe({ id: 'r0' }, started())
  expect(records).toHaveLength(4096)
  expect(collector.stats()).toMatchObject({ trackedRuns: 0, dropped: 2 })
  await collector.dispose()
})
it('rejects conflicting parent relationships without mixing root runs', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'a' }, started()); collector.observe({ id: 'b' }, started())
  collector.observe({ id: 'child', parentId: 'a' }, budget())
  collector.observe({ id: 'child', parentId: 'b' }, budget(3))
  collector.closeRoot('a'); collector.closeRoot('b')
  expect(records.filter(r => r.kind !== 'run-seal')).toHaveLength(3)
  expect(records.filter(r => r.kind === 'run-seal')).toEqual(expect.arrayContaining([expect.objectContaining({ complete: false })]))
  await collector.dispose()
})
it('drains events admitted while a background flush settles', async () => {
  const { collector, store } = setup()
  let queued = 0
  vi.mocked(store.enqueue).mockImplementation(() => { queued++; return true })
  vi.mocked(store.flush).mockImplementation(async () => {
    queued = 0
    if (vi.mocked(store.flush).mock.calls.length === 1) queueMicrotask(() => queueMicrotask(() => collector.observe({ id: 'root' }, budget())))
  })
  collector.observe({ id: 'root' }, started())
  await new Promise(resolve => setImmediate(resolve))
  expect(queued).toBe(0)
  await collector.dispose()
})
it('marks known sessions incomplete when parent metadata is malformed', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'root' }, started())
  collector.observe({ id: 'root', parentId: 'x'.repeat(16385) }, budget())
  collector.closeRoot('root')
  expect(records.at(-1)).toMatchObject({ complete: false, lostCount: 1 })
  await collector.dispose()
})
it('rejects empty session identifiers without admitting roots', async () => {
  const { collector, records } = setup()
  collector.observe({ id: '' }, started())
  expect(collector.stats()).toMatchObject({ trackedRuns: 0, dropped: 1 })
  expect(records).toHaveLength(0)
  await collector.dispose()
})
it('does not turn an unseen parent into a complete run after losing its child event', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'child', parentId: 'root' }, budget())
  collector.observe({ id: 'root' }, started())
  collector.closeRoot('root')
  expect(records.some(record => record.kind === 'run-seal' && record.complete)).toBe(false)
  await collector.dispose()
})
it('does not hide a rejected child event by later reparenting to a known root', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'root' }, started())
  collector.observe({ id: 'child', parentId: 'missing' }, budget(1))
  collector.observe({ id: 'child', parentId: 'root' }, budget(2))
  collector.closeRoot('root')
  expect(records).toHaveLength(2)
  expect(records.at(-1)).toMatchObject({ complete: false, observationCount: 1, lostCount: 1 })
  expect(collector.stats().dropped).toBe(2)
  await collector.dispose()
})
it('rejects novel children after retirement saturation while continuing known sessions', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'root' }, started())
  collector.observe({ id: 'known', parentId: 'root' }, budget(1))
  for (let i = 0; i < 2048; i++) collector.closeRoot(`closed-${i}`)
  collector.observe({ id: 'forgotten', parentId: 'missing' }, budget(1))
  collector.observe({ id: 'forgotten', parentId: 'root' }, budget(2))
  collector.observe({ id: 'novel', parentId: 'root' }, budget(1))
  collector.observe({ id: 'known', parentId: 'root' }, budget(2))
  collector.observe({ id: 'root' }, budget(2))
  collector.closeRoot('root')
  expect(records).toHaveLength(5)
  expect(records.at(-1)).toMatchObject({ complete: false, observationCount: 4, lostCount: 2 })
  await collector.dispose()
})
it('retires descendant identities when their run closes', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'a' }, started()); collector.observe({ id: 'b' }, started())
  collector.observe({ id: 'child', parentId: 'a' }, budget(1))
  collector.closeRoot('a')
  collector.observe({ id: 'child', parentId: 'b' }, budget(2))
  collector.closeRoot('b')
  expect(records).toHaveLength(5)
  expect(records.at(-1)).toMatchObject({ complete: false, observationCount: 1, lostCount: 1 })
  await collector.dispose()
})
it('retires identifiable unknown sessions rejected by a callback', async () => {
  const { collector, records } = setup()
  collector.reject('root')
  collector.observe({ id: 'root' }, started())
  collector.closeRoot('root')
  expect(records).toHaveLength(0)
  expect(collector.stats().dropped).toBe(2)
  await collector.dispose()
})
it('does not rebind an unknown child after invalid sequence or parent metadata', async () => {
  const { collector, records } = setup()
  collector.observe({ id: 'a' }, started()); collector.observe({ id: 'b' }, started())
  collector.observe({ id: 'bad-seq', parentId: 'a' }, budget(-1))
  collector.observe({ id: 'bad-parent', parentId: 'x'.repeat(16385) }, budget(1))
  collector.observe({ id: 'bad-seq', parentId: 'b' }, budget(2))
  collector.observe({ id: 'bad-parent', parentId: 'b' }, budget(2))
  collector.closeRoot('b')
  expect(records).toHaveLength(3)
  expect(records.at(-1)).toMatchObject({ complete: false, observationCount: 1, lostCount: 2 })
  await collector.dispose()
})
